- name: Deploy to Azure Container Instances
  uses: Azure/aci-deploy@v1
  with:
    # Name of the Resource Group in which the Container Instance will be created
    resource-group: ACIRG
    # The DNS Name Label for Container with Public IP
    dns-name-label: acidemoapp.westeurope.azurecontainer.io
    # Specify the fully qualified container image name. For example, "myregistry.azurecr.io/nginx:latest" or "python:3.7.2-alpine/"
    image: nginx
    # Location where the Container will be deployed
    location: westeurope
    # The Log Analytics Workspace Name or Id
    log-analytics-workspace: # optional
    # The Log Analytics Workspace Key
    log-analytics-workspace-key: # optional
    # The Log type to be used. Accepted Values are { ContainerInsights, ContainerInstanceLogs }
    log-type: # optional
    # Required Memory of the Containers in GB, accurate to one decimal place
    memory: # optional, default is 1.5
    # Name of the Container Group Instance
    name: acidemoapp
    # The OS type of the Containers. Accepted Values are  { Linux, Windows }
    os-type: # optional, default is Linux
    # The Ports to Open on the Container. Space seperate the ports for multiple values
    ports: # optional, default is 80
    # The Network protocol to use. Accepted Values are { TCP, UDP }
    protocol: # optional, default is TCP
    # The container image registry login server
    registry-login-server: # optional, default is 
    # Username to log in Container Image Registry Server
    registry-username: # optional, default is 
    # Password to log in Container Image Registry Server
    registry-password: # optional, default is 
    # Restart Policy for the container(s). Accepted Values are { Always, OnFailure, Never }
    restart-policy: # optional, default is Always
    # List of secure environment variables for the container. Space seperated values in "key=value" format
    secure-environment-variables: # optional, default is 
