on: [push, workflow_dispatch]
name: Build and deploy

jobs:
    build-and-deploy:
      if: github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
        # checkout the repo
        - name: Checkout GitHub Action
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: acr4devops.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t acr4devops.azurecr.io/devopsdemoapp:${{ event.run_id }} .
            docker push acr4devops.azurecr.io/devopsdemoapp:${{ event.run_id }}
            
        - name: Azure Kubernetes set context
          uses: azure/aks-set-context@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            resource-group: devopsaks
            cluster-name: aks4devops
        
        - name: Create imagepullsecret for Azure Container registry (ACR)
          uses: azure/k8s-create-secret@v1.1
          with:
            namespace: default
            container-registry-url: acr4devops.azurecr.io
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}            
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: devopsdemo-cr

        - name: Baking the helm chart to generate the manifests to deploy
          uses: Azure/k8s-bake@v1
          with:
            renderEngine: helm            
            helmChart: ./devopschart/
            helm-version: latest
            overrides: |
              image.tag:${{ event.run_id }}
          id: bake
            
        - name: Deploy app to AKS
          uses: azure/k8s-deploy@v1.3
          with:
            manifests: ${{ steps.bake.outputs.manifestsBundle }}
            images: |
              acr4devops.azurecr.io/devopsdemoapp:${{ event.run_id }}
            imagepullsecrets: |
              devopsdemo-cr
            strategy: blue-green
            route-method: ingress
            version-switch-buffer: 3
            namespace: default

    reject_green_deployment:
      if: github.event_name == 'workflow_dispatch'
      runs-on: ubuntu-latest
      steps:
        - name: Baking the helm chart to generate the manifests to deploy
          uses: Azure/k8s-bake@v1
          with:
            renderEngine: helm            
            helmChart: ./devopschart/
            helm-version: latest
            overrides: |
              image.tag:${{ event.run_id }}
          id: bake
            
        - name: Deploy app to AKS
          uses: azure/k8s-deploy@v1.3
          with:
            manifests: ${{ steps.bake.outputs.manifestsBundle }}
            images: |
              acr4devops.azurecr.io/devopsdemoapp:${{ event.run_id }}
            imagepullsecrets: |
              devopsdemo-cr
            strategy: blue-green
            route-method: ingress
            action: reject