on: [workflow_dispatch]
name: Reject Green

jobs:
    reject-green:
        runs-on: ubuntu-latest
        steps:       
        - uses: azure/docker-login@v1
          with:
            login-server: acr4devops.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: Azure Kubernetes set context
          uses: azure/aks-set-context@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            resource-group: devopsaks
            cluster-name: aks4devops
        
        - name: Create imagepullsecret for Azure Container registry (ACR)
          uses: azure/k8s-create-secret@v1.1
          with:
            namespace: default
            container-registry-url: acr4devops.azurecr.io
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}            
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: devopsdemo-cr

        - name: Baking the helm chart to generate the manifests to deploy
          uses: Azure/k8s-bake@v1
          with:
            # Acceptable values: helm or kompose or kustomize
            renderEngine: helm            
            helmChart: ./devopschart/
            helm-version: latest
            overrides: |
              image.tag:${{ github.sha }}
          id: bake
            
        - name: Deploy app to AKS
          uses: azure/k8s-deploy@v1.3
          with:
            manifests: ${{ steps.bake.outputs.manifestsBundle }}
            images: |
              acr4devops.azurecr.io/devopsdemoapp:${{ github.sha }}
            imagepullsecrets: |
              devopsdemo-cr
            strategy: blue-green
            route-method: ingress
            action: reject
